from __future__ import annotations

# Maps normalised tag string → (primary_genre, subgenre).
# Walk tags in weight order; first hit wins.
GENRE_MAP: dict[str, tuple[str, str]] = {
    # --- Electronic ---
    "electronic":           ("electronic", "electronic"),
    "electronica":          ("electronic", "electronic"),
    "edm":                  ("electronic", "electronic"),
    "house":                ("electronic", "house"),
    "deep house":           ("electronic", "deep house"),
    "tech house":           ("electronic", "tech house"),
    "progressive house":    ("electronic", "progressive house"),
    "acid house":           ("electronic", "acid house"),
    "afro house":           ("electronic", "afro house"),
    "melodic house":        ("electronic", "melodic house"),
    "techno":               ("electronic", "techno"),
    "minimal techno":       ("electronic", "minimal techno"),
    "industrial techno":    ("electronic", "industrial techno"),
    "melodic techno":       ("electronic", "melodic techno"),
    "trance":               ("electronic", "trance"),
    "progressive trance":   ("electronic", "progressive trance"),
    "psytrance":            ("electronic", "psytrance"),
    "psy trance":           ("electronic", "psytrance"),
    "uplifting trance":     ("electronic", "uplifting trance"),
    "drum and bass":        ("electronic", "drum and bass"),
    "dnb":                  ("electronic", "drum and bass"),
    "drum & bass":          ("electronic", "drum and bass"),
    "liquid drum and bass": ("electronic", "liquid drum and bass"),
    "neurofunk":            ("electronic", "neurofunk"),
    "jungle":               ("electronic", "jungle"),
    "dubstep":              ("electronic", "dubstep"),
    "brostep":              ("electronic", "dubstep"),
    "garage":               ("electronic", "uk garage"),
    "uk garage":            ("electronic", "uk garage"),
    "2-step":               ("electronic", "uk garage"),
    "bass music":           ("electronic", "bass music"),
    "grime":                ("electronic", "grime"),
    "electro":              ("electronic", "electro"),
    "electro house":        ("electronic", "electro house"),
    "big room":             ("electronic", "big room"),
    "future house":         ("electronic", "future house"),
    "ambient":              ("electronic", "ambient"),
    "dark ambient":         ("electronic", "dark ambient"),
    "drone":                ("electronic", "ambient"),
    "chillout":             ("electronic", "chillout"),
    "chill out":            ("electronic", "chillout"),
    "downtempo":            ("electronic", "downtempo"),
    "trip-hop":             ("electronic", "trip-hop"),
    "trip hop":             ("electronic", "trip-hop"),
    "breakbeat":            ("electronic", "breakbeat"),
    "breaks":               ("electronic", "breakbeat"),
    "nu-disco":             ("electronic", "nu-disco"),
    "nu disco":             ("electronic", "nu-disco"),
    "disco":                ("electronic", "disco"),
    "afrobeat":             ("electronic", "afrobeat"),
    "afro":                 ("electronic", "afrobeat"),
    "minimal":              ("electronic", "minimal"),
    "idm":                  ("electronic", "idm"),
    "experimental electronic": ("electronic", "experimental"),
    "noise":                ("electronic", "experimental"),
    "hard techno":          ("electronic", "hard techno"),
    "hardcore":             ("electronic", "hardcore"),
    "gabber":               ("electronic", "hardcore"),
    "hardstyle":            ("electronic", "hardstyle"),
    "rave":                 ("electronic", "rave"),
    "old school rave":      ("electronic", "rave"),
    "dance":                ("electronic", "dance"),
    "eurodance":            ("electronic", "dance"),
    "future bass":          ("electronic", "future bass"),
    "wave":                 ("electronic", "wave"),
    "dark wave":            ("electronic", "wave"),
    "synthwave":            ("electronic", "synthwave"),
    "retrowave":            ("electronic", "synthwave"),
    "lo-fi":                ("electronic", "lo-fi"),
    "lofi":                 ("electronic", "lo-fi"),
    "lo-fi hip hop":        ("electronic", "lo-fi"),
    # --- Hip-Hop / R&B ---
    "hip-hop":              ("hip-hop", "hip-hop"),
    "hip hop":              ("hip-hop", "hip-hop"),
    "rap":                  ("hip-hop", "rap"),
    "trap":                 ("hip-hop", "trap"),
    "cloud rap":            ("hip-hop", "cloud rap"),
    "boom bap":             ("hip-hop", "boom bap"),
    "conscious hip-hop":    ("hip-hop", "conscious hip-hop"),
    "r&b":                  ("r&b", "r&b"),
    "rnb":                  ("r&b", "r&b"),
    "soul":                 ("r&b", "soul"),
    "neo soul":             ("r&b", "neo soul"),
    "funk":                 ("r&b", "funk"),
    # --- Rock ---
    "rock":                 ("rock", "rock"),
    "alternative rock":     ("rock", "alternative rock"),
    "alternative":          ("rock", "alternative rock"),
    "indie rock":           ("rock", "indie rock"),
    "indie":                ("rock", "indie rock"),
    "classic rock":         ("rock", "classic rock"),
    "hard rock":            ("rock", "hard rock"),
    "metal":                ("rock", "metal"),
    "heavy metal":          ("rock", "heavy metal"),
    "punk rock":            ("rock", "punk rock"),
    "punk":                 ("rock", "punk rock"),
    "post-punk":            ("rock", "post-punk"),
    "grunge":               ("rock", "grunge"),
    "progressive rock":     ("rock", "progressive rock"),
    "shoegaze":             ("rock", "shoegaze"),
    "new wave":             ("rock", "new wave"),
    # --- Pop ---
    "pop":                  ("pop", "pop"),
    "synth-pop":            ("pop", "synth-pop"),
    "synthpop":             ("pop", "synth-pop"),
    "electropop":           ("pop", "electropop"),
    "dream pop":            ("pop", "dream pop"),
    "baroque pop":          ("pop", "pop"),
    # --- Jazz ---
    "jazz":                 ("jazz", "jazz"),
    "nu jazz":              ("jazz", "nu jazz"),
    "jazz fusion":          ("jazz", "jazz fusion"),
    # --- Classical ---
    "classical":            ("classical", "classical"),
    "orchestral":           ("classical", "orchestral"),
    # --- Reggae / Dub ---
    "reggae":               ("reggae", "reggae"),
    "dub":                  ("reggae", "dub"),
    "reggaeton":            ("latin", "reggaeton"),
    # --- Latin ---
    "latin":                ("latin", "latin"),
    "salsa":                ("latin", "salsa"),
}

# Tags from Last.fm that carry no genre signal — strip before classifying.
NOISE_TAGS: frozenset[str] = frozenset([
    "seen live", "favorite", "favourite", "loved", "love", "awesome", "best",
    "all", "albums i own", "check out", "under 2000 listeners", "beautiful",
    "chill", "relaxing", "great", "good", "nice", "cool", "amazing",
    "my favorite", "my favourite", "spotify", "youtube", "soundcloud",
    "male vocalists", "female vocalists", "singers", "bands",
])
